# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/xilinx-k26-som-2023.2.srcs/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/project_1_DPUCZDX8G_0.xci
# IP: The module: 'project_1_DPUCZDX8G_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_exp/fp_exp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_convert/fp_convert.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_div/fp_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_acc/fp_acc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_add/fp_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# XDC: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/project_1_DPUCZDX8G_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_DPUCZDX8G_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/project_1_DPUCZDX8G_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_DPUCZDX8G_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/xilinx-k26-som-2023.2.srcs/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/project_1_DPUCZDX8G_0.xci
# IP: The module: 'project_1_DPUCZDX8G_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_exp/fp_exp.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_convert/fp_convert.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_div/fp_div.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_acc/fp_acc.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/xci/sfm/fp_add/fp_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# XDC: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/project_1_DPUCZDX8G_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_DPUCZDX8G_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tikao/K26Based/Awl_K26/hardware/xilinx-k26-som-2023.2/project_1.gen/sources_1/bd/project_1/ip/project_1_DPUCZDX8G_0/project_1_DPUCZDX8G_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_DPUCZDX8G_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
